title: hagnimada
description: hagnimada personal website.
url: https://hagnimada.com
author: Adam Ingah

permalink: /:path/

exclude:
  - readme.md
  - Gemfile
  - Gemfile.lock
  - vendor
  - .claude

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
